// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/mohamed-gougam/kube-agent/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// TCPServers returns a TCPServerInformer.
	TCPServers() TCPServerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// TCPServers returns a TCPServerInformer.
func (v *version) TCPServers() TCPServerInformer {
	return &tCPServerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
