// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	k8snginxv1 "github.com/mohamed-gougam/kube-agent/pkg/apis/k8snginx/v1"
	versioned "github.com/mohamed-gougam/kube-agent/pkg/client/clientset/versioned"
	internalinterfaces "github.com/mohamed-gougam/kube-agent/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/mohamed-gougam/kube-agent/pkg/client/listers/k8snginx/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TCPServerInformer provides access to a shared informer and lister for
// TCPServers.
type TCPServerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.TCPServerLister
}

type tCPServerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTCPServerInformer constructs a new informer for TCPServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTCPServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTCPServerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTCPServerInformer constructs a new informer for TCPServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTCPServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().TCPServers(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().TCPServers(namespace).Watch(options)
			},
		},
		&k8snginxv1.TCPServer{},
		resyncPeriod,
		indexers,
	)
}

func (f *tCPServerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTCPServerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *tCPServerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&k8snginxv1.TCPServer{}, f.defaultInformer)
}

func (f *tCPServerInformer) Lister() v1.TCPServerLister {
	return v1.NewTCPServerLister(f.Informer().GetIndexer())
}
