// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/mohamed-gougam/kube-agent/pkg/apis/k8snginx/v1"
	scheme "github.com/mohamed-gougam/kube-agent/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TCPServersGetter has a method to return a TCPServerInterface.
// A group's client should implement this interface.
type TCPServersGetter interface {
	TCPServers(namespace string) TCPServerInterface
}

// TCPServerInterface has methods to work with TCPServer resources.
type TCPServerInterface interface {
	Create(*v1.TCPServer) (*v1.TCPServer, error)
	Update(*v1.TCPServer) (*v1.TCPServer, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.TCPServer, error)
	List(opts metav1.ListOptions) (*v1.TCPServerList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TCPServer, err error)
	TCPServerExpansion
}

// tCPServers implements TCPServerInterface
type tCPServers struct {
	client rest.Interface
	ns     string
}

// newTCPServers returns a TCPServers
func newTCPServers(c *K8sV1Client, namespace string) *tCPServers {
	return &tCPServers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tCPServer, and returns the corresponding tCPServer object, and an error if there is any.
func (c *tCPServers) Get(name string, options metav1.GetOptions) (result *v1.TCPServer, err error) {
	result = &v1.TCPServer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tcpservers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TCPServers that match those selectors.
func (c *tCPServers) List(opts metav1.ListOptions) (result *v1.TCPServerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.TCPServerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tcpservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tCPServers.
func (c *tCPServers) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tcpservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a tCPServer and creates it.  Returns the server's representation of the tCPServer, and an error, if there is any.
func (c *tCPServers) Create(tCPServer *v1.TCPServer) (result *v1.TCPServer, err error) {
	result = &v1.TCPServer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tcpservers").
		Body(tCPServer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tCPServer and updates it. Returns the server's representation of the tCPServer, and an error, if there is any.
func (c *tCPServers) Update(tCPServer *v1.TCPServer) (result *v1.TCPServer, err error) {
	result = &v1.TCPServer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tcpservers").
		Name(tCPServer.Name).
		Body(tCPServer).
		Do().
		Into(result)
	return
}

// Delete takes name of the tCPServer and deletes it. Returns an error if one occurs.
func (c *tCPServers) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tcpservers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tCPServers) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tcpservers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tCPServer.
func (c *tCPServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TCPServer, err error) {
	result = &v1.TCPServer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tcpservers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
