// Code generated by lister-gen. DO NOT EDIT.

package v1

// TCPServerListerExpansion allows custom methods to be added to
// TCPServerLister.
type TCPServerListerExpansion interface{}

// TCPServerNamespaceListerExpansion allows custom methods to be added to
// TCPServerNamespaceLister.
type TCPServerNamespaceListerExpansion interface{}
