apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserver-coffee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcpserver-coffee
  template:
    metadata:
      labels:
        app: tcpserver-coffee
    spec:
      containers:
      - name: tcpserver-coffee
        image: mgnginx/tcpserver-example:latest
        ports:
        - containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver-coffee-svc
spec:
  ports:
  - port: 54321
    targetPort: 12345
    protocol: TCP
    name: sometcpport
  selector:
    app: tcpserver-coffee