apiVersion: v1
kind: Service
metadata:
  name: kube-agent
  namespace: kube-agent
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: tcpss1
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: tcpss2
  selector:
    app: kube-agent